import { invoke } from "@tauri-apps/api/core";
import { useCallback, useState } from "react";
import type { Dispatch, SetStateAction } from "react";
import type { Midi } from "../../types/midi";
import { getErrorMessage } from "../../utils/sampleMapper";

type UseMidiLibraryParams = { readonly pageLimit: number; readonly directoryPath: string; readonly midiTagFilterId: number | null; readonly setError: (message: string | null) => void };
type MidiSelection = { readonly setSelectedMidi: Dispatch<SetStateAction<Midi | null>>; readonly setSelectedMidiIds: Dispatch<SetStateAction<Set<number>>> };

export function useMidiLibrary({ pageLimit, directoryPath, midiTagFilterId, setError }: UseMidiLibraryParams) {
  const [midis, setMidis] = useState<Midi[]>([]); const [debouncedMidiSearch, setDebouncedMidiSearch] = useState("");
  const [isLoadingMoreMidi, setIsLoadingMoreMidi] = useState(false); const [isLoadingPreviousMidi, setIsLoadingPreviousMidi] = useState(false);
  const [currentMidiOffset, setCurrentMidiOffset] = useState(0); const [canLoadMoreMidi, setCanLoadMoreMidi] = useState(true);
  const [canLoadPreviousMidi, setCanLoadPreviousMidi] = useState(false); const [lastFetchCountMidi, setLastFetchCountMidi] = useState<number | null>(null);
  const loadPage = useCallback(async (query: string, offset: number, overrideDirectoryPath?: string) => {
    const payload = { limit: pageLimit, offset, directoryPath: (overrideDirectoryPath ?? directoryPath) || null, tagId: midiTagFilterId };
    return query.trim() ? invoke<Midi[]>("search_midis_paginated", { query, ...payload }) : invoke<Midi[]>("list_midis_paginated", payload);
  }, [directoryPath, midiTagFilterId, pageLimit]);
  const hasActiveFilters = useCallback((overrideDirectoryPath?: string) => debouncedMidiSearch.trim().length > 0 || midiTagFilterId !== null || (overrideDirectoryPath ?? directoryPath).length > 0, [debouncedMidiSearch, directoryPath, midiTagFilterId]);
  const replacePage = useCallback((rows: Midi[], offset: number) => { setMidis(rows); setCurrentMidiOffset(offset); setLastFetchCountMidi(rows.length); setCanLoadMoreMidi(rows.length >= pageLimit); setCanLoadPreviousMidi(offset > 0); }, [pageLimit]);
  const runMidiSearch = useCallback(async (query: string) => { try { setDebouncedMidiSearch(query); replacePage(await loadPage(query, 0), 0); } catch (error) { console.error("MIDI search failed:", error); } }, [loadPage, replacePage]);
  const loadMoreMidi = useCallback(async () => { if (isLoadingMoreMidi || !canLoadMoreMidi) return; setIsLoadingMoreMidi(true); try { const rows = await loadPage(debouncedMidiSearch, currentMidiOffset + midis.length); setMidis((previous) => { const ids = new Set(previous.map((midi) => midi.id)); return [...previous, ...rows.filter((midi) => !ids.has(midi.id))]; }); setLastFetchCountMidi(rows.length); setCanLoadMoreMidi(rows.length >= pageLimit); setCanLoadPreviousMidi(currentMidiOffset > 0); } catch (error) { setError(getErrorMessage(error)); } finally { setIsLoadingMoreMidi(false); } }, [canLoadMoreMidi, currentMidiOffset, debouncedMidiSearch, isLoadingMoreMidi, loadPage, midis.length, pageLimit, setError]);
  const loadPreviousMidi = useCallback(async () => { if (isLoadingPreviousMidi || !canLoadPreviousMidi || currentMidiOffset === 0) return; setIsLoadingPreviousMidi(true); try { const offset = Math.max(0, currentMidiOffset - pageLimit); const rows = await loadPage(debouncedMidiSearch, offset); setMidis((previous) => { const ids = new Set(previous.map((midi) => midi.id)); return [...rows.filter((midi) => !ids.has(midi.id)), ...previous]; }); setCurrentMidiOffset(offset); setLastFetchCountMidi(rows.length); setCanLoadPreviousMidi(offset > 0); setCanLoadMoreMidi(true); } catch (error) { setError(getErrorMessage(error)); } finally { setIsLoadingPreviousMidi(false); } }, [canLoadPreviousMidi, currentMidiOffset, debouncedMidiSearch, isLoadingPreviousMidi, loadPage, pageLimit, setError]);
  const loadAroundMidi = useCallback(async (targetId: number) => { setIsLoadingMoreMidi(true); setIsLoadingPreviousMidi(true); try { if (hasActiveFilters()) { replacePage(await loadPage(debouncedMidiSearch, 0), 0); } else { const rows = await invoke<Midi[]>("list_midis_around_id", { targetId, limit: pageLimit }); replacePage(rows, Math.max(0, targetId - Math.floor(pageLimit / 2))); } } catch (error) { setError(getErrorMessage(error)); } finally { setIsLoadingMoreMidi(false); setIsLoadingPreviousMidi(false); } }, [debouncedMidiSearch, hasActiveFilters, loadPage, pageLimit, replacePage, setError]);
  const loadMidiByPath = useCallback(async (path: string, selection: MidiSelection, overrideDirectoryPath?: string) => { try { const row = await invoke<Midi | null>("get_midi", { path }); if (!row) return null; if (hasActiveFilters(overrideDirectoryPath)) replacePage(await loadPage(debouncedMidiSearch, 0, overrideDirectoryPath), 0); else { const rows = await invoke<Midi[]>("list_midis_around_id", { targetId: row.id, limit: pageLimit }); replacePage(rows, Math.max(0, row.id - Math.floor(pageLimit / 2))); } selection.setSelectedMidi(row); selection.setSelectedMidiIds(new Set([row.id])); return row; } catch (error) { console.error("Failed to load MIDI:", error); return null; } }, [debouncedMidiSearch, hasActiveFilters, loadPage, pageLimit, replacePage]);
  return { midis, setMidis, debouncedMidiSearch, runMidiSearch, loadMidiByPath, loadMoreMidi, loadPreviousMidi, loadAroundMidi, isLoadingMoreMidi, isLoadingPreviousMidi, canLoadMoreMidi, canLoadPreviousMidi, lastFetchCountMidi, setLastFetchCountMidi };
}
