import { invoke } from "@tauri-apps/api/core";
import { useState } from "react";
import type { Dispatch, SetStateAction } from "react";
import type { Midi, MidiTagRow } from "../../types/midi";
import { getErrorMessage } from "../../utils/sampleMapper";

type UseMidiTagsParams = { readonly midis: Midi[]; readonly setMidis: Dispatch<SetStateAction<Midi[]>>; readonly selectedMidi: Midi | null; readonly setSelectedMidi: Dispatch<SetStateAction<Midi | null>>; readonly setSelectedMidiIds: Dispatch<SetStateAction<Set<number>>>; readonly runMidiSearch: (query: string) => Promise<void>; readonly fetchAllMidiPaths: () => Promise<void>; readonly debouncedMidiSearch: string; readonly midiTagFilterId: number | null; readonly setError: (message: string | null) => void };
export function useMidiTags({ midis, setMidis, selectedMidi, setSelectedMidi, setSelectedMidiIds, runMidiSearch, fetchAllMidiPaths, debouncedMidiSearch, midiTagFilterId, setError }: UseMidiTagsParams) {
  const [midiTags, setMidiTags] = useState<MidiTagRow[]>([]); const [confirmOpen, setConfirmOpen] = useState(false); const [pendingTrashMidiId, setPendingTrashMidiId] = useState<number | null>(null); const [midiTagModalOpen, setMidiTagModalOpen] = useState(false); const [midiTagEditOpen, setMidiTagEditOpen] = useState(false); const [midiTagEditTarget, setMidiTagEditTarget] = useState<Midi | null>(null); const [midiTagEditTargetIds, setMidiTagEditTargetIds] = useState<number[]>([]);
  const refreshTags = async () => setMidiTags(await invoke<MidiTagRow[]>("get_midi_tags"));
  const handleMidiTagChange = async (midiIds: number | number[], tagId: number | null) => { try { const ids = Array.isArray(midiIds) ? midiIds : [midiIds]; await Promise.all(ids.map((midiId) => invoke("set_midi_file_tag", { midiId, tagId }))); const tagName = tagId === null ? "" : midiTags.find((tag) => tag.id === tagId)?.name ?? ""; setMidis((previous) => previous.map((midi) => ids.includes(midi.id) ? { ...midi, tag_name: tagName } : midi)); if (midiTagFilterId !== null && tagId !== midiTagFilterId) await runMidiSearch(debouncedMidiSearch); } catch (error) { setError(`Failed to set MIDI tag: ${error}`); } };
  const handleAddMidiTag = async (name: string) => { try { await invoke<number>("add_midi_tag", { name }); await refreshTags(); } catch (error) { setError(`Failed to add MIDI tag: ${error}`); } };
  const handleDeleteMidiTag = async (id: number) => { try { await invoke<number>("delete_midi_tag", { id }); await refreshTags(); } catch (error) { setError(`Failed to delete MIDI tag: ${error}`); } };
  const handleUpdateMidiTag = async (id: number, name: string) => { try { await invoke<number>("update_midi_tag", { id, name }); await refreshTags(); } catch (error) { setError(`Failed to update MIDI tag: ${error}`); } };
  const requestTrashMidi = (id: number) => { setPendingTrashMidiId(id); setConfirmOpen(true); };
  const confirmTrashMidi = async () => { if (pendingTrashMidiId === null) return; const path = midis.find((midi) => midi.id === pendingTrashMidiId)?.path; if (!path) { setConfirmOpen(false); setPendingTrashMidiId(null); return; } try { await invoke<string>("send_to_trash", { path }); await runMidiSearch(debouncedMidiSearch); await fetchAllMidiPaths(); if (selectedMidi?.id === pendingTrashMidiId) { setSelectedMidi(null); setSelectedMidiIds(new Set()); } } catch (error) { setError(getErrorMessage(error)); } finally { setConfirmOpen(false); setPendingTrashMidiId(null); } };
  return { midiTags, setMidiTags, confirmOpen, setConfirmOpen, pendingTrashMidiId, setPendingTrashMidiId, midiTagModalOpen, setMidiTagModalOpen, midiTagEditOpen, setMidiTagEditOpen, midiTagEditTarget, setMidiTagEditTarget, midiTagEditTargetIds, setMidiTagEditTargetIds, handleMidiTagChange, handleAddMidiTag, handleDeleteMidiTag, handleUpdateMidiTag, requestTrashMidi, confirmTrashMidi };
}
