import { act, renderHook, waitFor } from "@testing-library/react";
import { StrictMode } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { FreesoundInvoke } from "../useFreesoundWorkspace";
import { useFreesoundWorkspace } from "../useFreesoundWorkspace";

const invokeMock = vi.fn<FreesoundInvoke>();

describe("useFreesoundWorkspace preview", () => {
  beforeEach(() => { invokeMock.mockReset(); });
  afterEach(() => { vi.restoreAllMocks(); });
  it("consumes raw Tauri preview bytes and cleans preview URLs when replacing and unmounting", async () => {
    const revokeObjectURL = vi.spyOn(URL, "revokeObjectURL"); const blobs: Blob[] = []; const createObjectURL = vi.spyOn(URL, "createObjectURL").mockImplementation((blob) => { if (!(blob instanceof Blob)) throw new Error("expected a preview Blob"); blobs.push(blob); return `blob:${blobs.length}`; });
    invokeMock.mockResolvedValueOnce({ configured: true }).mockResolvedValueOnce(new Uint8Array([0, 127, 255]).buffer).mockResolvedValueOnce(new Uint8Array([1]).buffer); const { result, unmount } = renderHook(() => useFreesoundWorkspace(true, invokeMock)); await waitFor(() => expect(result.current.credential).toBe("configured")); await act(async () => { await result.current.fetchPreview("https://preview"); }); await act(async () => { await result.current.fetchPreview("https://preview-two"); }); unmount();
    expect(createObjectURL).toHaveBeenCalledTimes(2); const firstBlob = blobs[0]; if (!firstBlob) throw new Error("expected first preview blob"); expect([...new Uint8Array(await firstBlob.arrayBuffer())]).toEqual([0, 127, 255]); expect(revokeObjectURL).toHaveBeenCalledWith("blob:1"); expect(revokeObjectURL).toHaveBeenCalledWith("blob:2");
  });
  it("stops and revokes previews when disabled or before search replaces results", async () => {
    const revokeObjectURL = vi.spyOn(URL, "revokeObjectURL"); vi.spyOn(URL, "createObjectURL").mockReturnValue("blob:preview"); invokeMock.mockResolvedValueOnce({ configured: true }).mockResolvedValueOnce(new Uint8Array([1]).buffer).mockResolvedValueOnce({ page: 2, pageSize: 20, totalCount: 0, hasPrevious: true, hasNext: false, sounds: [] }).mockResolvedValueOnce(new Uint8Array([2]).buffer); const { result, rerender } = renderHook(({ enabled }) => useFreesoundWorkspace(enabled, invokeMock), { initialProps: { enabled: true } }); await waitFor(() => expect(result.current.credential).toBe("configured"));
    await act(async () => { await result.current.fetchPreview("https://preview"); }); expect(result.current.previewUrl).toBe("blob:preview"); await act(async () => { await result.current.search("kick", 2); }); expect(result.current.previewUrl).toBeNull(); expect(revokeObjectURL).toHaveBeenCalledWith("blob:preview"); await act(async () => { await result.current.fetchPreview("https://preview"); }); await act(async () => { rerender({ enabled: false }); }); expect(result.current.previewUrl).toBeNull(); expect(revokeObjectURL).toHaveBeenCalledWith("blob:preview");
  });
  it("does not invoke duplicate synchronous searches", async () => {
    let resolveSearch: (value: unknown) => void = () => undefined; const searchResponse = new Promise<unknown>((resolve) => { resolveSearch = resolve; }); invokeMock.mockResolvedValueOnce({ configured: true }).mockReturnValueOnce(searchResponse); const { result } = renderHook(() => useFreesoundWorkspace(true, invokeMock)); await waitFor(() => expect(result.current.credential).toBe("configured")); await act(async () => { void result.current.search("kick", 1); void result.current.search("kick", 1); }); expect(invokeMock).toHaveBeenCalledTimes(2); resolveSearch({ page: 1, pageSize: 20, totalCount: 0, hasPrevious: false, hasNext: false, sounds: [] }); await act(async () => { await searchResponse; });
  });
  it("does not create a preview URL when disabled before a deferred preview resolves", async () => {
    let resolvePreview: (value: unknown) => void = () => undefined; const previewResponse = new Promise<unknown>((resolve) => { resolvePreview = resolve; }); const createObjectURL = vi.spyOn(URL, "createObjectURL"); const revokeObjectURL = vi.spyOn(URL, "revokeObjectURL"); invokeMock.mockResolvedValueOnce({ configured: true }).mockReturnValueOnce(previewResponse); const { result, rerender } = renderHook(({ enabled }) => useFreesoundWorkspace(enabled, invokeMock), { initialProps: { enabled: true } }); await waitFor(() => expect(result.current.credential).toBe("configured")); let request: Promise<void> = Promise.resolve(); await act(async () => { request = result.current.fetchPreview("https://preview"); }); await act(async () => { rerender({ enabled: false }); }); await act(async () => { resolvePreview(new Uint8Array([1]).buffer); await request; }); expect(result.current.previewUrl).toBeNull(); expect(revokeObjectURL).toHaveBeenCalledTimes(createObjectURL.mock.calls.length);
  });
  it("does not create a preview URL when unmounted before a deferred preview resolves", async () => {
    let resolvePreview: (value: unknown) => void = () => undefined; const previewResponse = new Promise<unknown>((resolve) => { resolvePreview = resolve; }); const createObjectURL = vi.spyOn(URL, "createObjectURL"); const revokeObjectURL = vi.spyOn(URL, "revokeObjectURL"); invokeMock.mockResolvedValueOnce({ configured: true }).mockReturnValueOnce(previewResponse); const { result, unmount } = renderHook(() => useFreesoundWorkspace(true, invokeMock)); await waitFor(() => expect(result.current.credential).toBe("configured")); let request: Promise<void> = Promise.resolve(); await act(async () => { request = result.current.fetchPreview("https://preview"); }); await act(async () => { unmount(); }); await act(async () => { resolvePreview(new Uint8Array([1]).buffer); await request; }); expect(revokeObjectURL).toHaveBeenCalledTimes(createObjectURL.mock.calls.length);
  });
  it("commits a deferred preview in StrictMode while the workspace remains active", async () => {
    let resolvePreview: (value: unknown) => void = () => undefined; const previewResponse = new Promise<unknown>((resolve) => { resolvePreview = resolve; }); vi.spyOn(URL, "createObjectURL").mockReturnValue("blob:strict-preview"); invokeMock.mockImplementation((command) => command === "fetch_freesound_preview" ? previewResponse : Promise.resolve({ configured: true })); const { result } = renderHook(() => useFreesoundWorkspace(true, invokeMock), { wrapper: StrictMode }); await waitFor(() => expect(result.current.credential).toBe("configured")); let request: Promise<void> = Promise.resolve(); await act(async () => { request = result.current.fetchPreview("https://preview"); }); await act(async () => { resolvePreview(new Uint8Array([1]).buffer); await request; }); expect(result.current.previewUrl).toBe("blob:strict-preview");
  });
  it("revokes a deferred preview response after stopPreview invalidates it", async () => {
    let resolvePreview: (value: unknown) => void = () => undefined; const previewResponse = new Promise<unknown>((resolve) => { resolvePreview = resolve; }); const createObjectURL = vi.spyOn(URL, "createObjectURL").mockReturnValue("blob:stopped-preview"); const revokeObjectURL = vi.spyOn(URL, "revokeObjectURL"); invokeMock.mockResolvedValueOnce({ configured: true }).mockReturnValueOnce(previewResponse); const { result } = renderHook(() => useFreesoundWorkspace(true, invokeMock)); await waitFor(() => expect(result.current.credential).toBe("configured")); let request: Promise<void> = Promise.resolve(); await act(async () => { request = result.current.fetchPreview("https://preview"); result.current.stopPreview(); }); await act(async () => { resolvePreview(new Uint8Array([1]).buffer); await request; }); expect(result.current.previewUrl).toBeNull(); expect(revokeObjectURL).toHaveBeenCalledTimes(createObjectURL.mock.calls.length);
  });
  it("rejects preview values that are not raw Tauri IPC bytes", async () => {
    invokeMock.mockResolvedValueOnce({ configured: true }).mockResolvedValueOnce([0, 255]).mockResolvedValueOnce({ bytes: [1] }); const { result } = renderHook(() => useFreesoundWorkspace(true, invokeMock)); await waitFor(() => expect(result.current.credential).toBe("configured")); await act(async () => { await result.current.fetchPreview("https://preview"); }); expect(result.current.error).toContain("request failed"); await act(async () => { await result.current.fetchPreview("https://preview"); }); expect(result.current.error).toContain("request failed");
  });
  it("cleans a failed current preview through stopPreview generation handling", async () => {
    const revokeObjectURL = vi.spyOn(URL, "revokeObjectURL"); vi.spyOn(URL, "createObjectURL").mockReturnValue("blob:preview"); invokeMock.mockResolvedValueOnce({ configured: true }).mockResolvedValueOnce(new Uint8Array([1]).buffer); const { result } = renderHook(() => useFreesoundWorkspace(true, invokeMock)); await waitFor(() => expect(result.current.credential).toBe("configured")); await act(async () => { await result.current.fetchPreview("https://preview"); }); act(() => { result.current.failPreview("blob:preview"); }); expect(result.current.previewUrl).toBeNull(); expect(result.current.error).toBe("Audio preview could not be played."); expect(revokeObjectURL).toHaveBeenCalledWith("blob:preview");
  });
});
