import {
  AppErrorBanner, AppMainPane, AppModals, Header, PlayerBar, RescanPrompt, ScannerOverlay, SettingsModal,
} from "../components";
import { ProviderBrowser } from "../components/ProviderBrowser/ProviderBrowser";
import type { useAppRuntime } from "./useAppRuntime";

type AppViewProps = { readonly runtime: ReturnType<typeof useAppRuntime> };

export function AppView({ runtime }: AppViewProps) {
  const { autoPlayOnSelect, collectionState, derivedState, directoryClickFiltering, externalApiCommands, handleSampleSelectWithRecent, handleViewModeChange, instrumentColorCoding, libraryMigration, midiState, providerBrowser, providerBrowserMode, providerDownloadRoot, providerDownloadRootPicker, sampleListRef, sampleState, scanState, setAutoPlayOnSelect, setInstrumentColorCoding, setDirectoryClickFiltering, setPlayerBarRef, setProviderBrowserMode, setProviderDownloadRoot, setShowSampleMetadataQuality, showProviderControls, showSampleMetadataQuality, uiState, playerBarRef, midiListRef } = runtime;
  return <div style={{ background: "#080a0f", height: "100vh", fontFamily: "'Courier New', monospace", color: "#e2e8f0", display: "flex", flexDirection: "column", overflow: "hidden", minWidth: 0 }}>
    <Header sampleCount={sampleState.samples.length} scanned={scanState.scanned} isDragOver={uiState.isDragOver} onBackToSources={() => { void runtime.clearActiveProvider(); }} onGoBack={() => { void providerBrowser.goBack(); }} onGoForward={() => { void providerBrowser.goForward(); }} viewMode={uiState.viewMode} onViewModeChange={handleViewModeChange} onScanClick={() => { void scanState.handleScanClick(); }} onReScanClick={() => { void scanState.handleReScanClick(); }} onSettingsClick={() => uiState.setSettingsOpen(true)} onReload={() => { void sampleState.handleSearch(sampleState.filters.search); }} showProviderControls={showProviderControls} />
    <RescanPrompt isOpen={scanState.rescanPromptOpen} path={scanState.rescanPendingPath} isIncremental={true} onRescan={async () => { if (!scanState.rescanPendingPath) return; scanState.setRescanPromptOpen(false); await scanState.performScan(scanState.rescanPendingPath); scanState.setRescanPendingPath(null); }} onSkip={() => { scanState.setRescanPendingPath(null); scanState.setRescanPromptOpen(false); }} />
    <AppErrorBanner error={scanState.error} onRetry={() => { void sampleState.handleRetry(); }} />
    {scanState.scanning && <ScannerOverlay progress={scanState.scanProgress} onDone={() => {}} />}
    <AppMainPane uiState={uiState} scanState={scanState} sampleState={sampleState} midiState={midiState} playerBarRef={playerBarRef} sampleListRef={sampleListRef} midiListRef={midiListRef} displayedSamples={derivedState.displayedSamples} samplePaths={derivedState.displayedSamplePaths} collections={collectionState.collections} activeCollectionId={collectionState.activeCollectionId} isCollectionView={collectionState.isCollectionView} onSelectCollection={(collectionId) => { void collectionState.selectCollection(collectionId); }} onClearCollection={collectionState.clearCollection} filteredMidis={derivedState.filteredMidis} instrumentColorCoding={instrumentColorCoding} directoryClickFiltering={directoryClickFiltering} showSampleMetadataQuality={showSampleMetadataQuality} handleSampleSelectWithRecent={handleSampleSelectWithRecent} getSampleProcessingSettings={derivedState.sampleProcessingState.getSettingsForSample} providerBrowser={<ProviderBrowser activeProvider={providerBrowser.activeProvider} mode={providerBrowserMode} onBrowse={(provider) => { void providerBrowser.selectProvider(provider); }} status={providerBrowser.status} viewportRef={providerBrowser.viewportRef} />} />
    {uiState.viewMode === "sample" && sampleState.selected && <PlayerBar key={sampleState.selected.id} ref={setPlayerBarRef} sample={sampleState.selected} path={derivedState.selectedSamplePath} autoPlay={autoPlayOnSelect && sampleState.selected.id !== externalApiCommands.previewSampleId} processingSettings={derivedState.sampleProcessingState.selectedSettings} onProcessingSettingsChange={derivedState.sampleProcessingState.updateSelectedSettings} onProcessingSettingsReset={derivedState.sampleProcessingState.resetSelectedSettings} onProcessingSettingsClear={derivedState.sampleProcessingState.clearSelectedSettings} onClose={() => { playerBarRef.current?.stop(); sampleState.setSelected(null); }} />}
    <SettingsModal isOpen={uiState.settingsOpen} onClose={() => uiState.setSettingsOpen(false)} sampleCount={sampleState.samples.length} autoPlayOnSelect={autoPlayOnSelect} onAutoPlayChange={setAutoPlayOnSelect} instrumentColorCoding={instrumentColorCoding} onInstrumentColorCodingChange={setInstrumentColorCoding} directoryClickFiltering={directoryClickFiltering} onDirectoryClickFilteringChange={setDirectoryClickFiltering} showSampleMetadataQuality={showSampleMetadataQuality} onShowSampleMetadataQualityChange={setShowSampleMetadataQuality} providerDownloadRoot={providerDownloadRoot} onSelectProviderDownloadRoot={() => { void providerDownloadRootPicker.selectProviderDownloadRoot(); }} onClearProviderDownloadRoot={() => setProviderDownloadRoot(null)} providerBrowserMode={providerBrowserMode} onProviderBrowserModeChange={(mode) => { void providerBrowser.changeMode(mode).then((closedMode) => { if (closedMode) setProviderBrowserMode(closedMode); }); }} onDatabaseExport={() => { void libraryMigration.handleExportDatabase(); }} onDatabaseImport={() => { void libraryMigration.handleImportDatabase(); }} databaseMigrationBusy={libraryMigration.migrationBusy} databaseMigrationStatus={libraryMigration.migrationStatus} />
    <AppModals sampleState={sampleState} midiState={midiState} />
  </div>;
}
